"""create link table

Revision ID: 92194ecbdf40
Revises: 
Create Date: 2024-10-07 21:08:52.686672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92194ecbdf40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=300), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=True),
    sa.Column('deletion_date', sa.DateTime(), nullable=True),
    sa.Column('max_visits', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
